runtime: nodejs
env: flex
env_variables:
  INSTANCE_CONNECTION_NAME: "zippy-haven-379715:us-central1:my-first-instance"
beta_settings:
  cloud_sql_instances: "zippy-haven-379715:us-central1:my-first-instance"
